title = "Packager"
gitSourceBranch = "main"

[[classOrder]]
classes = ["Bind", "CameraUtil", "Platform"]

[[classOrder]]
section = "Signal"
classes = ["Signal", "Connection"]

[[classOrder]]
classes = ["Color3Helper", "Displays", ]

[[classOrder]]
section = "Storage"
classes = ["Storage", "BaseStorage", "PlayerStorage", "OrderedStorage"]

[home]
enabled = true
includeReadme = true

[docusaurus]
tagline = "Utility modules!!"