title = "dToolkit"
gitSourceBranch = "main"


[[classOrder]]
section = "Client"
classes = ["Bind", "CameraUtil", "Platform", "UIUtil"]

[[classOrder]]
section = "Signal"
classes = ["Signal", "Connection"]

[[classOrder]]
section = "Storage"
classes = ["Storage", "BaseStorage", "PlayerStorage", "OrderedStorage"]

[home]
enabled = true
includeReadme = true

[docusaurus]
tagline = "A versatile and simple toolkit made for everyone!"